// Public-repository hygiene: what must never be TRACKED here.
//
// This repository is public. Its planning material (specs, lane briefs, review
// reports, audit bundles) is private and lives in `atelier-internal`; the `moss`
// engine's renderer package is unpublished; and a path from a
// maintainer's home directory says which machine the code was written on.
// `.gitignore` keeps all three out of an ordinary `git add`; this test is the
// backstop for `git add -f`, a renamed ignore file, or a fresh clone that
// forgot the rule. It reads the index, not the working tree, because only
// tracked files are published.

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));

function trackedFiles() {
  const out = execFileSync("git", ["-C", ROOT, "ls-files", "-z"], { encoding: "utf8" });
  return out.split("\0").filter(Boolean);
}

// Path shapes that are private by construction, whatever their content.
const FORBIDDEN_PATHS = [
  [/^specs\//, "planning specs belong in atelier-internal"],
  [/^themes\/[^/]+\/vendor\/moss-web-renderer\//, "the moss engine's renderer package is unpublished"],
  [/\.wasm$/, "no compiled binaries in this history"],
  [/^docs\/evidence\/moss-engine-mvp\//, "regenerated by the Moss browser test, never tracked"],
];

// A real home directory has a real layout under it. Synthetic fixture homes
// (`/home/operator`, `/home/u/.nvm/...`) do not match; a pasted
// `/home/<you>/dev/...` or `/Users/<you>/Documents/...` does.
const MACHINE_PATH = /\/(?:home|Users)\/[A-Za-z][A-Za-z0-9._-]*\/(?:dev|Documents|Downloads|\.config|\.local|\.cache|\.rustup|\.cargo)\//;

// Text-bearing extensions worth scanning; binaries and the three.js bundle are
// skipped (the bundle is upstream code, not something written here).
const TEXT = /\.(?:mjs|js|cjs|ts|json|md|yml|yaml|txt|sh|css|html|svg|toml|ini|env|d\.ts)$/;
const SKIP_CONTENT = [/^themes\/[^/]+\/vendor\//];

test("no private path shape is tracked", () => {
  const offenders = [];
  for (const file of trackedFiles()) {
    for (const [pattern, why] of FORBIDDEN_PATHS) {
      if (pattern.test(file)) offenders.push(`${file}: ${why}`);
    }
  }
  assert.deepEqual(offenders, []);
});

test("no tracked text file names a real home directory", () => {
  const offenders = [];
  for (const file of trackedFiles()) {
    if (!TEXT.test(file) || SKIP_CONTENT.some((p) => p.test(file))) continue;
    if (file === "test-system/public-hygiene.test.mjs") continue;
    const text = readFileSync(resolve(ROOT, file), "utf8");
    const lines = text.split("\n");
    for (let i = 0; i < lines.length; i += 1) {
      if (MACHINE_PATH.test(lines[i])) offenders.push(`${file}:${i + 1}`);
    }
  }
  assert.deepEqual(offenders, []);
});
